### ISSUE TITLE
CIM - References Sections

### ISSUE THREAD

**Issue by Cyb3rWard0g** [OTRF/OSSEM#79]
References Links on entities fields
* References added to description field
  * Example: [1](https://......com)

```yaml
name: Image
type: string
description: Adding References in this field section [1](http://..com)
```
